create table public.carts (
  id uuid primary key default gen_random_uuid(),
  customer_id uuid references public.customers(id) on delete set null,
  guest_token_hash text unique,
  status public.cart_status not null default 'active',
  currency char(3) not null default 'PKR' check (currency = 'PKR'),
  last_activity_at timestamptz not null default timezone('utc', now()),
  expires_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  check (customer_id is not null or guest_token_hash is not null)
);
create index carts_customer_status_idx on public.carts(customer_id, status) where customer_id is not null;
create index carts_activity_idx on public.carts(last_activity_at desc);

create table public.cart_items (
  id uuid primary key default gen_random_uuid(),
  cart_id uuid not null references public.carts(id) on delete cascade,
  variant_id uuid not null references public.product_variants(id) on delete restrict,
  quantity integer not null check (quantity > 0 and quantity <= 99),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (cart_id, variant_id)
);
create index cart_items_variant_idx on public.cart_items(variant_id);

create table public.wishlists (
  id uuid primary key default gen_random_uuid(),
  customer_id uuid not null references public.customers(id) on delete cascade,
  name text not null default 'Saved',
  is_default boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);
create unique index wishlists_one_default_idx on public.wishlists(customer_id) where is_default;

create table public.wishlist_items (
  wishlist_id uuid not null references public.wishlists(id) on delete cascade,
  variant_id uuid not null references public.product_variants(id) on delete cascade,
  created_at timestamptz not null default timezone('utc', now()),
  primary key (wishlist_id, variant_id)
);

create table public.discounts (
  id uuid primary key default gen_random_uuid(),
  code extensions.citext not null unique,
  name text not null,
  description text,
  discount_type public.discount_type not null,
  percentage_bps integer check (percentage_bps is null or percentage_bps between 1 and 10000),
  fixed_amount_pkr bigint check (fixed_amount_pkr is null or fixed_amount_pkr > 0),
  max_discount_pkr bigint check (max_discount_pkr is null or max_discount_pkr > 0),
  min_order_pkr bigint not null default 0 check (min_order_pkr >= 0),
  usage_limit integer check (usage_limit is null or usage_limit > 0),
  usage_limit_per_customer integer check (usage_limit_per_customer is null or usage_limit_per_customer > 0),
  starts_at timestamptz,
  ends_at timestamptz,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  check (ends_at is null or starts_at is null or ends_at > starts_at),
  check (
    (discount_type = 'percentage' and percentage_bps is not null and fixed_amount_pkr is null)
    or (discount_type = 'fixed_amount' and fixed_amount_pkr is not null and percentage_bps is null)
    or (discount_type = 'free_shipping' and percentage_bps is null and fixed_amount_pkr is null)
  )
);

create table public.discount_rules (
  id uuid primary key default gen_random_uuid(),
  discount_id uuid not null references public.discounts(id) on delete cascade,
  rule_type text not null check (rule_type in ('product','category','collection','customer','first_order','minimum_quantity','shipping_zone')),
  rule_config jsonb not null default '{}'::jsonb check (jsonb_typeof(rule_config) = 'object'),
  created_at timestamptz not null default timezone('utc', now())
);
create index discount_rules_discount_idx on public.discount_rules(discount_id);

create table public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number bigint generated by default as identity (start with 100001) unique,
  customer_id uuid references public.customers(id) on delete set null,
  guest_checkout boolean not null default false,
  contact_name text not null,
  contact_email extensions.citext,
  contact_phone text not null,
  contact_whatsapp text,
  status public.order_status not null default 'pending_verification',
  verification_status public.verification_status not null default 'pending',
  cod_settlement_status public.cod_settlement_status not null default 'not_due',
  currency char(3) not null default 'PKR' check (currency = 'PKR'),
  subtotal_pkr bigint not null check (subtotal_pkr >= 0),
  discount_pkr bigint not null default 0 check (discount_pkr >= 0),
  shipping_pkr bigint not null default 0 check (shipping_pkr >= 0),
  tax_pkr bigint not null default 0 check (tax_pkr >= 0),
  total_pkr bigint not null check (total_pkr >= 0),
  shipping_rule_id uuid references public.shipping_rules(id) on delete set null,
  discount_id uuid references public.discounts(id) on delete set null,
  idempotency_key text not null unique,
  customer_note text,
  internal_note text,
  placed_at timestamptz not null default timezone('utc', now()),
  confirmed_at timestamptz,
  cancelled_at timestamptz,
  delivered_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  check (customer_id is not null or guest_checkout),
  check (discount_pkr <= subtotal_pkr),
  check (total_pkr = greatest(0::bigint, subtotal_pkr - discount_pkr + shipping_pkr + tax_pkr))
);
create index orders_customer_created_idx on public.orders(customer_id, created_at desc) where customer_id is not null;
create index orders_status_created_idx on public.orders(status, created_at desc);
create index orders_verification_status_idx on public.orders(verification_status, created_at desc);
create index orders_cod_status_idx on public.orders(cod_settlement_status, created_at desc);
create index orders_phone_idx on public.orders(contact_phone);

alter table public.carts add column converted_order_id uuid references public.orders(id) on delete set null;
create unique index carts_converted_order_idx on public.carts(converted_order_id) where converted_order_id is not null;

create table public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id uuid references public.products(id) on delete set null,
  variant_id uuid references public.product_variants(id) on delete set null,
  sku text not null,
  product_name text not null,
  variant_name text not null,
  variant_snapshot jsonb not null default '{}'::jsonb check (jsonb_typeof(variant_snapshot) = 'object'),
  unit_price_pkr bigint not null check (unit_price_pkr >= 0),
  quantity integer not null check (quantity > 0 and quantity <= 99),
  line_total_pkr bigint not null check (line_total_pkr >= 0),
  created_at timestamptz not null default timezone('utc', now()),
  check (line_total_pkr = unit_price_pkr * quantity)
);
create index order_items_order_idx on public.order_items(order_id);
create index order_items_variant_idx on public.order_items(variant_id) where variant_id is not null;

create table public.order_addresses (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  address_type public.address_type not null default 'shipping',
  recipient_name text not null,
  phone text not null,
  whatsapp_number text,
  address_line1 text not null,
  address_line2 text,
  city text not null,
  district text,
  province text not null,
  postal_code text,
  country_code char(2) not null default 'PK' check (country_code = 'PK'),
  delivery_instructions text,
  created_at timestamptz not null default timezone('utc', now()),
  unique (order_id, address_type)
);

create table public.order_status_history (
  id bigint generated always as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  from_status public.order_status,
  to_status public.order_status not null,
  note text,
  changed_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default timezone('utc', now())
);
create index order_status_history_order_created_idx on public.order_status_history(order_id, created_at);

create table public.cod_verifications (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  attempt_number smallint not null check (attempt_number > 0),
  method public.verification_method not null,
  status public.verification_status not null default 'pending',
  provider_message_id text,
  initiated_by uuid references auth.users(id) on delete set null,
  verified_by uuid references auth.users(id) on delete set null,
  note text,
  sent_at timestamptz,
  responded_at timestamptz,
  verified_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  unique (order_id, attempt_number)
);
create index cod_verifications_order_status_idx on public.cod_verifications(order_id, status);

create table public.cod_settlements (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null unique references public.orders(id) on delete restrict,
  shipment_id uuid,
  courier_name text,
  courier_reference text,
  expected_pkr bigint not null check (expected_pkr >= 0),
  collected_pkr bigint check (collected_pkr is null or collected_pkr >= 0),
  received_pkr bigint check (received_pkr is null or received_pkr >= 0),
  status public.cod_settlement_status not null default 'not_due',
  discrepancy_note text,
  reconciled_by uuid references auth.users(id) on delete set null,
  collected_at timestamptz,
  received_at timestamptz,
  reconciled_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);
create index cod_settlements_status_idx on public.cod_settlements(status, created_at desc);

create table public.shipments (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete restrict,
  courier_name text,
  courier_service text,
  tracking_number text,
  status public.shipment_status not null default 'pending',
  shipped_at timestamptz,
  delivered_at timestamptz,
  expected_delivery_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);
create index shipments_order_idx on public.shipments(order_id);
create unique index shipments_tracking_idx on public.shipments(courier_name, tracking_number) where tracking_number is not null;

alter table public.cod_settlements add constraint cod_settlements_shipment_fk foreign key (shipment_id) references public.shipments(id) on delete set null;

create table public.delivery_attempts (
  id uuid primary key default gen_random_uuid(),
  shipment_id uuid not null references public.shipments(id) on delete cascade,
  attempt_number smallint not null check (attempt_number > 0),
  status public.delivery_attempt_status not null,
  reason_code text,
  reason_detail text,
  attempted_at timestamptz not null,
  next_attempt_at timestamptz,
  recorded_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default timezone('utc', now()),
  unique (shipment_id, attempt_number)
);
create index delivery_attempts_shipment_idx on public.delivery_attempts(shipment_id, attempt_number);

create table public.rto_records (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null unique references public.orders(id) on delete restrict,
  shipment_id uuid references public.shipments(id) on delete set null,
  status public.rto_status not null default 'initiated',
  reason_code text,
  reason_detail text,
  initiated_at timestamptz not null default timezone('utc', now()),
  received_at timestamptz,
  resolved_at timestamptz,
  resolution_note text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);
create index rto_records_status_idx on public.rto_records(status, created_at desc);

create table public.returns (
  id uuid primary key default gen_random_uuid(),
  return_number bigint generated by default as identity (start with 500001) unique,
  order_id uuid not null references public.orders(id) on delete restrict,
  customer_id uuid references public.customers(id) on delete set null,
  status public.return_status not null default 'requested',
  reason_code text not null,
  reason_detail text,
  resolution public.return_resolution,
  requested_at timestamptz not null default timezone('utc', now()),
  approved_at timestamptz,
  received_at timestamptz,
  completed_at timestamptz,
  handled_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);
create index returns_order_idx on public.returns(order_id);
create index returns_status_idx on public.returns(status, created_at desc);

create table public.return_items (
  id uuid primary key default gen_random_uuid(),
  return_id uuid not null references public.returns(id) on delete cascade,
  order_item_id uuid not null references public.order_items(id) on delete restrict,
  quantity integer not null check (quantity > 0),
  item_condition text,
  resolution public.return_resolution,
  created_at timestamptz not null default timezone('utc', now()),
  unique (return_id, order_item_id)
);

create table public.discount_redemptions (
  id uuid primary key default gen_random_uuid(),
  discount_id uuid not null references public.discounts(id) on delete restrict,
  order_id uuid not null unique references public.orders(id) on delete cascade,
  customer_id uuid references public.customers(id) on delete set null,
  amount_pkr bigint not null check (amount_pkr >= 0),
  created_at timestamptz not null default timezone('utc', now())
);
create index discount_redemptions_discount_idx on public.discount_redemptions(discount_id, created_at desc);
create index discount_redemptions_customer_idx on public.discount_redemptions(customer_id, discount_id) where customer_id is not null;

create table public.reviews (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null references public.products(id) on delete cascade,
  customer_id uuid references public.customers(id) on delete set null,
  order_item_id uuid unique references public.order_items(id) on delete set null,
  rating smallint not null check (rating between 1 and 5),
  title text,
  body text,
  status public.review_status not null default 'pending',
  verified_purchase boolean not null default false,
  published_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);
create index reviews_product_status_idx on public.reviews(product_id, status, created_at desc);

create table public.support_tickets (
  id uuid primary key default gen_random_uuid(),
  ticket_number bigint generated by default as identity (start with 700001) unique,
  customer_id uuid references public.customers(id) on delete set null,
  order_id uuid references public.orders(id) on delete set null,
  subject text not null,
  status public.support_status not null default 'open',
  priority public.notification_priority not null default 'normal',
  assigned_to uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  resolved_at timestamptz
);
create index support_tickets_customer_idx on public.support_tickets(customer_id, created_at desc) where customer_id is not null;
create index support_tickets_status_idx on public.support_tickets(status, priority, created_at desc);

create table public.support_messages (
  id uuid primary key default gen_random_uuid(),
  ticket_id uuid not null references public.support_tickets(id) on delete cascade,
  author_user_id uuid references auth.users(id) on delete set null,
  author_customer_id uuid references public.customers(id) on delete set null,
  body text not null,
  is_internal boolean not null default false,
  created_at timestamptz not null default timezone('utc', now()),
  check (author_user_id is not null or author_customer_id is not null)
);
create index support_messages_ticket_created_idx on public.support_messages(ticket_id, created_at);

create table public.notifications (
  id uuid primary key default gen_random_uuid(),
  recipient_user_id uuid references auth.users(id) on delete cascade,
  recipient_customer_id uuid references public.customers(id) on delete cascade,
  event_key text not null,
  title text not null,
  body text not null,
  priority public.notification_priority not null default 'normal',
  entity_type text,
  entity_id uuid,
  data jsonb not null default '{}'::jsonb check (jsonb_typeof(data) = 'object'),
  read_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  check (recipient_user_id is not null or recipient_customer_id is not null)
);
create index notifications_user_unread_idx on public.notifications(recipient_user_id, created_at desc) where recipient_user_id is not null and read_at is null;
create index notifications_customer_idx on public.notifications(recipient_customer_id, created_at desc) where recipient_customer_id is not null;
create index notifications_entity_idx on public.notifications(entity_type, entity_id) where entity_id is not null;

create table public.notification_deliveries (
  id uuid primary key default gen_random_uuid(),
  notification_id uuid not null references public.notifications(id) on delete cascade,
  channel public.notification_channel not null,
  status public.notification_delivery_status not null default 'pending',
  provider text,
  provider_message_id text,
  attempt_count smallint not null default 0 check (attempt_count >= 0),
  last_error_code text,
  last_error_message text,
  queued_at timestamptz not null default timezone('utc', now()),
  sent_at timestamptz,
  delivered_at timestamptz,
  failed_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (notification_id, channel)
);
create index notification_deliveries_status_idx on public.notification_deliveries(status, queued_at);

create table public.notification_preferences (
  customer_id uuid primary key references public.customers(id) on delete cascade,
  in_app_order_updates boolean not null default true,
  email_order_updates boolean not null default true,
  whatsapp_order_updates boolean not null default true,
  email_marketing boolean not null default false,
  whatsapp_marketing boolean not null default false,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table public.email_events (
  id uuid primary key default gen_random_uuid(),
  notification_delivery_id uuid references public.notification_deliveries(id) on delete set null,
  provider text not null,
  provider_event_id text unique,
  event_type text not null,
  recipient_email extensions.citext,
  payload jsonb not null default '{}'::jsonb check (jsonb_typeof(payload) = 'object'),
  occurred_at timestamptz not null,
  created_at timestamptz not null default timezone('utc', now())
);
create index email_events_type_occurred_idx on public.email_events(event_type, occurred_at desc);

create table public.abandoned_carts (
  id uuid primary key default gen_random_uuid(),
  cart_id uuid not null unique references public.carts(id) on delete cascade,
  customer_id uuid references public.customers(id) on delete set null,
  email extensions.citext,
  phone text,
  status public.abandoned_cart_status not null default 'detected',
  detected_at timestamptz not null default timezone('utc', now()),
  notified_at timestamptz,
  recovered_at timestamptz,
  expires_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);
create index abandoned_carts_status_idx on public.abandoned_carts(status, detected_at);

create table public.activity_logs (
  id bigint generated always as identity primary key,
  actor_user_id uuid references auth.users(id) on delete set null,
  customer_id uuid references public.customers(id) on delete set null,
  event_type text not null,
  entity_type text,
  entity_id uuid,
  metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata) = 'object'),
  created_at timestamptz not null default timezone('utc', now())
);
create index activity_logs_customer_created_idx on public.activity_logs(customer_id, created_at desc) where customer_id is not null;
create index activity_logs_entity_idx on public.activity_logs(entity_type, entity_id, created_at desc) where entity_id is not null;

create table public.audit_logs (
  id bigint generated always as identity primary key,
  actor_user_id uuid references auth.users(id) on delete set null,
  action text not null,
  entity_type text not null,
  entity_id uuid,
  before_data jsonb,
  after_data jsonb,
  request_id text,
  ip_address inet,
  user_agent text,
  created_at timestamptz not null default timezone('utc', now()),
  check (before_data is null or jsonb_typeof(before_data) = 'object'),
  check (after_data is null or jsonb_typeof(after_data) = 'object')
);
create index audit_logs_actor_created_idx on public.audit_logs(actor_user_id, created_at desc) where actor_user_id is not null;
create index audit_logs_entity_idx on public.audit_logs(entity_type, entity_id, created_at desc) where entity_id is not null;

create trigger carts_updated_at before update on public.carts for each row execute function app_private.set_updated_at();
create trigger cart_items_updated_at before update on public.cart_items for each row execute function app_private.set_updated_at();
create trigger wishlists_updated_at before update on public.wishlists for each row execute function app_private.set_updated_at();
create trigger discounts_updated_at before update on public.discounts for each row execute function app_private.set_updated_at();
create trigger orders_updated_at before update on public.orders for each row execute function app_private.set_updated_at();
create trigger cod_settlements_updated_at before update on public.cod_settlements for each row execute function app_private.set_updated_at();
create trigger shipments_updated_at before update on public.shipments for each row execute function app_private.set_updated_at();
create trigger rto_records_updated_at before update on public.rto_records for each row execute function app_private.set_updated_at();
create trigger returns_updated_at before update on public.returns for each row execute function app_private.set_updated_at();
create trigger reviews_updated_at before update on public.reviews for each row execute function app_private.set_updated_at();
create trigger support_tickets_updated_at before update on public.support_tickets for each row execute function app_private.set_updated_at();
create trigger notification_deliveries_updated_at before update on public.notification_deliveries for each row execute function app_private.set_updated_at();
create trigger notification_preferences_updated_at before update on public.notification_preferences for each row execute function app_private.set_updated_at();
create trigger abandoned_carts_updated_at before update on public.abandoned_carts for each row execute function app_private.set_updated_at();
